package com.javaex.exception;

public class ArrayException {
    public static void main(String[] args) {
        int[] intArray = new int[]{3, 6, 9};
        try{
            System.out.println(intArray[3]);
        }catch (Exception e){

        }

    }
}
